from pathlib import Path

PATH = Path("app/src/main/java/com/surafel/audio/EqualizerActivity.kt")
s = PATH.read_text(encoding="utf-8")

def replace(old: str, new: str, name: str) -> None:
    global s
    if old not in s:
        raise SystemExit(f"Equalizer patch anchor missing: {name}")
    s = s.replace(old, new, 1)

replace('import android.content.Context\n', 'import android.app.AlertDialog\nimport android.content.Context\n', 'AlertDialog import')
replace('    private var enabled = true\n    private var reverbIndex = 0\n', '    private var enabled = true\n    private var selectedPreset = "CUSTOM"\n    private var reverbIndex = 0\n', 'selected preset state')
replace('        content.addView(buildPresetSection(), LinearLayout.LayoutParams(-1, dp(178)))\n', '        content.addView(buildPresetSection(), LinearLayout.LayoutParams(-1, dp(184)))\n', 'preset section height')

replace('''    private fun buildHeader(): View = LinearLayout(this).apply {\n        orientation = LinearLayout.HORIZONTAL\n        gravity = Gravity.CENTER_VERTICAL\n        setPadding(dp(14), 0, dp(10), 0)\n        setBackgroundColor(Color.rgb(7, 20, 45))\n''','''    private fun buildHeader(): View = LinearLayout(this).apply {\n        orientation = LinearLayout.HORIZONTAL\n        gravity = Gravity.CENTER_VERTICAL\n        setPadding(dp(14), 0, dp(10), 0)\n        setBackgroundColor(if (enabled) Color.rgb(7, 20, 45) else Color.TRANSPARENT)\n''','header background')
replace('''            value = enabled\n            setOnCheckedChangeListener { checked ->\n                enabled = checked\n                setEffectsEnabled(checked)\n                refreshContentAlpha()\n            }\n''','''            value = enabled\n            setOnCheckedChangeListener { checked ->\n                enabled = checked\n                setEffectsEnabled(checked)\n                refreshContentAlpha()\n                this@EqualizerActivity.root.setBackgroundColor(if (checked) Color.rgb(7, 20, 45) else Color.TRANSPARENT)\n                this@EqualizerActivity.root.getChildAt(0)?.setBackgroundColor(if (checked) Color.rgb(7, 20, 45) else Color.TRANSPARENT)\n            }\n''','header toggle')

replace('''    private fun buildBandCard(): View = cleanCard().apply {\n        addView(sectionTitle("Equalizer bands"))\n        status = TextView(this@EqualizerActivity).apply {\n            text = "AUDIO ENGINE • LIVE CONTROLS"\n            textSize = 10f\n            includeFontPadding = false\n            setTextColor(Color.rgb(128, 178, 231))\n            letterSpacing = .03f\n        }\n        addView(status, LinearLayout.LayoutParams(-1, dp(22)))\n        val bandRow = LinearLayout(this@EqualizerActivity).apply {\n            orientation = LinearLayout.HORIZONTAL\n            gravity = Gravity.CENTER\n        }\n        addBandViews(bandRow)\n        addView(bandRow, LinearLayout.LayoutParams(-1, dp(238)))\n    }\n''','''    private fun buildBandCard(): View = LinearLayout(this).apply {\n        orientation = LinearLayout.VERTICAL\n        setPadding(dp(2), dp(4), dp(2), dp(2))\n        setBackgroundColor(Color.TRANSPARENT)\n        addView(sectionTitle("Equalizer bands", "↻ Reset") { resetBands() })\n        status = TextView(this@EqualizerActivity).apply {\n            text = "AUDIO ENGINE • LIVE CONTROLS"\n            textSize = 10f\n            includeFontPadding = false\n            setTextColor(Color.rgb(128, 178, 231))\n            letterSpacing = .03f\n        }\n        addView(status, LinearLayout.LayoutParams(-1, dp(22)))\n        val bandRow = LinearLayout(this@EqualizerActivity).apply {\n            orientation = LinearLayout.HORIZONTAL\n            gravity = Gravity.CENTER\n        }\n        addBandViews(bandRow)\n        addView(bandRow, LinearLayout.LayoutParams(-1, dp(238)))\n    }\n''','free Equalizer bands')

replace('''    private fun buildReverbCard(): View = cleanCard().apply {\n        addView(sectionTitle("Reverb"))\n        reverbValue = UiButton(this@EqualizerActivity, "${reverbDisplayName(reverbIndex)}   ›").apply {\n            gravity = Gravity.CENTER_VERTICAL\n            setPadding(dp(14), 0, dp(14), 0)\n            setOnClickListener { cycleReverb() }\n        }\n        addView(reverbValue, LinearLayout.LayoutParams(-1, dp(48)))\n    }\n''','''    private fun buildReverbCard(): View = cleanCard().apply {\n        addView(sectionTitle("Reverb"))\n        reverbValue = UiButton(this@EqualizerActivity, "${reverbDisplayName(reverbIndex)}   ›").apply {\n            gravity = Gravity.CENTER_VERTICAL\n            setPadding(dp(14), 0, dp(14), 0)\n            setOnClickListener { showReverbChooser() }\n        }\n        addView(reverbValue, LinearLayout.LayoutParams(-1, dp(48)))\n    }\n''','reverb chooser button')

replace('''    private fun applyBand(uiIndex: Int, frequency: Int, db: Float) {\n        val safe = db.coerceIn(-15f, 15f)\n        val level = (safe * 100f).roundToInt().coerceIn(eqMin, eqMax).toShort()\n        try { nearestRealBand(frequency)?.let { equalizer?.setBandLevel(it, level) } } catch (_: Throwable) {}\n        prefs.edit().putFloat("eq_ui_${tenBand}_$uiIndex", safe).apply()\n    }\n''','''    private fun applyBand(uiIndex: Int, frequency: Int, db: Float) {\n        val safe = db.coerceIn(-15f, 15f)\n        val level = (safe * 100f).roundToInt().coerceIn(eqMin, eqMax).toShort()\n        try { nearestRealBand(frequency)?.let { equalizer?.setBandLevel(it, level) } } catch (_: Throwable) {}\n        prefs.edit().putFloat("eq_ui_${tenBand}_$uiIndex", safe).apply()\n        if (selectedPreset == "CUSTOM") {\n            prefs.edit().putFloat("eq_custom_${tenBand}_$uiIndex", safe).apply()\n        }\n    }\n''','custom persistence')

replace('''    private fun applyPreset(name: String) {\n        val values = when (name) {\n            "CUSTOM" -> FloatArray(if (tenBand) 10 else 5) { prefs.getFloat("eq_ui_${tenBand}_$it", 0f) }\n''','''    private fun applyPreset(name: String) {\n        if (name != "CUSTOM" && selectedPreset == "CUSTOM") saveCustomSnapshotFromCurrent()\n        selectedPreset = name\n        val values = when (name) {\n            "CUSTOM" -> FloatArray(if (tenBand) 10 else 5) { prefs.getFloat("eq_custom_${tenBand}_$it", prefs.getFloat("eq_ui_${tenBand}_$it", 0f)) }\n''','custom restore')

replace('''    private fun cycleReverb() {\n        reverbIndex = (reverbIndex + 1) % reverbNames.size\n        reverbValue.text = "${reverbDisplayName(reverbIndex)}   ›"\n        try {\n            presetReverb?.preset = reverbPresets[reverbIndex]\n            presetReverb?.enabled = enabled && reverbIndex != 0\n        } catch (_: Throwable) {}\n        prefs.edit().putInt("eq_reverb", reverbIndex).apply()\n    }\n''','''    private fun cycleReverb() {\n        showReverbChooser()\n    }\n\n    private fun showReverbChooser() {\n        val names = arrayOf("None", "Small Room", "Medium Room", "Big Room", "Concert Hall", "Arena", "Studio Vocal")\n        val descriptions = arrayOf(\n            "No added ambience.",\n            "Light echo for everyday listening.",\n            "Add natural depth and balanced space.",\n            "Create a wider, more immersive feel.",\n            "Bring the atmosphere of a live concert.",\n            "Adds depth and a grand sense of space.",\n            "Make vocals clearer and more present."\n        )\n        var pending = reverbIndex.coerceIn(0, 5)\n        val items = Array(names.size) { i -> "${names[i]}\\n${descriptions[i]}" }\n        AlertDialog.Builder(this)\n            .setTitle("Choose Reverb")\n            .setSingleChoiceItems(items, pending) { _, which -> pending = which }\n            .setNegativeButton("Cancel", null)\n            .setPositiveButton("Apply") { _, _ -> applyReverbChoice(pending) }\n            .show()\n    }\n\n    private fun applyReverbChoice(index: Int) {\n        val safe = index.coerceIn(0, 5)\n        reverbIndex = safe\n        reverbValue.text = "${reverbDisplayName(reverbIndex)}   ›"\n        try {\n            presetReverb?.preset = reverbPresets[reverbIndex]\n            presetReverb?.enabled = enabled && reverbIndex != 0\n        } catch (_: Throwable) {}\n        prefs.edit().putInt("eq_reverb", reverbIndex).apply()\n    }\n''','full reverb chooser')

replace('''    private fun resetEnhancers() {\n''','''    private fun saveCustomSnapshotFromCurrent() {\n        val count = if (tenBand) 10 else 5\n        val edit = prefs.edit()\n        for (i in 0 until count) {\n            val v = if (i < bandViews.size) bandViews[i].value else prefs.getFloat("eq_ui_${tenBand}_$i", 0f)\n            edit.putFloat("eq_custom_${tenBand}_$i", v.coerceIn(-15f, 15f))\n        }\n        edit.apply()\n    }\n\n    private fun ensureCustomSnapshot() {\n        if (!prefs.contains("eq_custom_${tenBand}_0")) saveCustomSnapshotFromCurrent()\n    }\n\n    private fun resetBands() {\n        selectedPreset = "CUSTOM"\n        val count = if (tenBand) 10 else 5\n        val edit = prefs.edit()\n        for (i in 0 until count) {\n            edit.putFloat("eq_ui_${tenBand}_$i", 0f)\n            edit.putFloat("eq_custom_${tenBand}_$i", 0f)\n            if (i < bandViews.size) {\n                bandViews[i].value = 0f\n                applyBand(i, bandViews[i].frequency, 0f)\n                bandViews[i].invalidate()\n            }\n        }\n        edit.apply()\n        selectPreset("CUSTOM")\n        Toast.makeText(this, "Equalizer reset", Toast.LENGTH_SHORT).show()\n    }\n\n    private fun resetEnhancers() {\n''','band reset')

replace('''        renderBands()\n        refreshContentAlpha()\n    }\n''','''        ensureCustomSnapshot()\n        renderBands()\n        refreshContentAlpha()\n    }\n''','custom initialization')

replace('''                MotionEvent.ACTION_DOWN, MotionEvent.ACTION_MOVE -> {\n                    parent?.requestDisallowInterceptTouchEvent(true)\n                    val ratio = ((bottom - event.y) / (bottom - top)).coerceIn(0f, 1f)\n''','''                MotionEvent.ACTION_DOWN, MotionEvent.ACTION_MOVE -> {\n                    parent?.requestDisallowInterceptTouchEvent(true)\n                    if (event.actionMasked == MotionEvent.ACTION_DOWN) {\n                        selectedPreset = "CUSTOM"\n                        selectPreset("CUSTOM")\n                    }\n                    val ratio = ((bottom - event.y) / (bottom - top)).coerceIn(0f, 1f)\n''','manual slider custom state')

PATH.write_text(s, encoding="utf-8")
print("Equalizer UI patch applied successfully")
